# Datenstrom Yellow extension settings

Extension: Meta
Version: 1.0.1
Description: Meta data for humans and machines.
Developer: Anna Svensson
Contributor: Steffen Schultz
Tag: feature
DownloadUrl: https://github.com/annaesvensson/yellow-meta/archive/refs/heads/main.zip
DocumentationUrl: https://github.com/annaesvensson/yellow-meta
DocumentationLanguage: en, de, sv
Published: 2026-09-25 19:06:44
Status: maintained
system/workers/meta.php: meta.php, create, update
